from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
import io
import datetime

def generate_requisition_doc(content: str, official_name: str = "Authorized Officer"):
    """
    Creates a formatted Ministry Internal Memo (.docx).
    """
    doc = Document()
    
    # 1. Ministry Header (Professional Styling)
    header = doc.add_heading('INTERNAL MEMO', 0)
    header.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # 2. Meta Data Table (Cleaner than plain text)
    table = doc.add_table(rows=4, cols=2)
    table.autofit = False
    table.columns[0].width = Inches(1.5)
    
    # Fill Table
    data = [
        ("DATE:", datetime.date.today().strftime("%d %B %Y")),
        ("TO:", "Permanent Secretary"),
        ("FROM:", official_name),
        ("SUBJECT:", "REQUISITION FOR FUNDS (Generated by Senna)")
    ]
    
    for i, (label, value) in enumerate(data):
        row = table.rows[i]
        row.cells[0].text = label
        row.cells[1].text = value
        # Bold the labels
        row.cells[0].paragraphs[0].runs[0].font.bold = True

    doc.add_paragraph('_' * 70) # Horizontal Line

    # 3. Body Content
    # We add the AI's approved text, removing the "Chat" syntax if any
    clean_content = content.replace("✅", "").replace("**", "")
    body_paragraph = doc.add_paragraph(clean_content)
    body_paragraph.alignment = WD_ALIGN_PARAGRAPH.JUSTIFY

    # 4. Signature Block
    doc.add_paragraph('\n\n\n') # Spacing
    doc.add_paragraph('__________________________')
    doc.add_paragraph(f'{official_name}')
    doc.add_paragraph('Requisitioning Officer')
    
    # 5. Save to Memory Buffer (Virtual File)
    buffer = io.BytesIO()
    doc.save(buffer)
    buffer.seek(0)
    
    return buffer